name: OxiUtils
version: '${project.version}'
main: fr.oxidayzz.Main
author: Oxidayzz

commands:
  host:
    description:
    usage:
  cohost:
    description:
    usage:
  listworld:
    description:
    usage:
  listhost:
    description:
    usage: