name: OxiUtils
version: '1.0-SNAPSHOT'
main: fr.oxidayzz.Main
author: Oxidayzz

commands:
  host:
    description:
    usage:
  cohost:
    description:
    usage:
  listworld:
    description:
    usage:
  listhost:
    description:
    usage: